.TH "func_recv" 3 "Martes, 19 de Abril de 2016" "Version 1" "ClienteIRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
func_recv \- func_recv 
Hilo de recepcion de mensajes del server\&.
.SH "SYNOPSIS"
.PP
.PP
.nf
 #include  <cabeceras.h>
   #include  <clientfuncs.h>

 void* func_recv ( void* thr_info )
.fi
.PP
.SH "DESCRIPCIÓN"
.PP
Esta funcion se encarga de recibir y procesar los mensajes recibidos que son enviados por el servidor\&.
.PP
Recibe como parametros thr_info, donde se encuentra la informacion para el envio\&.
.SH "RETORNO"
.PP
No retorna nada\&.
.SH "AUTOR"
.PP
Francisco Andreu Sanz (francisco.andreu@estudiante.uam.es) Javier Martínez Hernández (javier.maritnez@estudiante.uam.es) 
.PP
 
