.TH "func_ping" 3 "Martes, 19 de Abril de 2016" "Version 1" "ClienteIRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
func_ping \- func_ping 
Realiza el envio del mensaje /PING de manera periodica al servidor\&.
.SH "SYNOPSIS"
.PP
.PP
.nf
 #include  <cabeceras.h>
   #include  <clientfuncs.h>

 void* func_ping ( void* thr_info )
.fi
.PP
.SH "DESCRIPCIÓN"
.PP
Esta funcion genera y envia al servidor el mensaje /PING de manera periodica mediante el uso de hilos\&.
.PP
Recibe como parametros thr_info, donde se encuentra la informacion para el envio\&.
.SH "RETORNO"
.PP
No retorna nada\&.
.SH "AUTOR"
.PP
Francisco Andreu Sanz (francisco.andreu@estudiante.uam.es) Javier Martínez Hernández (javier.maritnez@estudiante.uam.es) 
.PP
 
